# Generated by Django 5.2.14 on 2026-05-16 20:59

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customer_support', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customermessage',
            name='category',
        ),
        migrations.RemoveField(
            model_name='customermessage',
            name='email',
        ),
        migrations.AlterField(
            model_name='customermessage',
            name='status',
            field=models.CharField(choices=[('OPEN', 'Open'), ('PENDING', 'Pending'), ('RESOLVED', 'Resolved')], default='OPEN', max_length=20),
        ),
        migrations.AlterField(
            model_name='customermessage',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='messages', to=settings.AUTH_USER_MODEL),
        ),
    ]
