# Generated by Django 5.2.14 on 2026-05-16 20:32

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('customer_support', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='DailySummary',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('summary_text', models.TextField()),
                ('total_messages', models.IntegerField(default=0)),
                ('urgent_issues', models.IntegerField(default=0)),
                ('generated_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='AIAnalysis',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category', models.CharField(max_length=50)),
                ('priority', models.CharField(max_length=20)),
                ('sentiment', models.CharField(max_length=20)),
                ('summary', models.TextField()),
                ('draft_reply', models.TextField()),
                ('action_required', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('message', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='customer_support.customermessage')),
            ],
        ),
        migrations.CreateModel(
            name='AutomationTask',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('task_type', models.CharField(max_length=100)),
                ('status', models.CharField(choices=[('Pending', 'Pending'), ('Running', 'Running'), ('Success', 'Success'), ('Failed', 'Failed')], default='Pending', max_length=20)),
                ('result', models.TextField(blank=True, null=True)),
                ('retry_count', models.IntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('message', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='customer_support.customermessage')),
            ],
        ),
    ]
